### ISSUE TITLE
Problem with creating a server

### ISSUE THREAD

**Issue by AkumaCipher** [LunaPixelStudios/Fantasy-Realm#5]
I unfortunately have a problem when I try to start it, it marks this:
`User did not agree to Mojang's EULA.
eula.txt present. Moving on...
Starting server...
Minecraft version: "1.16.5"
Forge version: "36.2.35"
Java version:
Picked up _JAVA_OPTIONS: -Xmx8G
java version "18.0.2" 2022-07-19
Java(TM) SE Runtime Environment (build 18.0.2+9-61)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2+9-61, mixed mode, sharing)
Java args: "-Xmx5G"
Picked up _JAVA_OPTIONS: -Xmx8G
2022-07-26 21:48:10,633 main WARN Advanced terminal features are not available in this environment
[21:48:10] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.35, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[21:48:10] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 18.0.2 by Oracle Corporation
Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x7fc2413d) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x7fc2413d
        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:45)
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:45)
        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:43)`

And I don't know what to really do, I've seen online it might be because of mods but I don't know which one :/

**Comment by SHXRKIEgg** [comment]
You are trying to use java 18 on 1.16.5 which needs java 8, uninstall java above 11
